# 1D Array 

## creating array

In [3]:
from array import *
a1 = array('i',[1,2,3,4,5,6])
a2 = array('d',[1.3,1.5,1.8])
print(a1)
print(a2)

array('i', [1, 2, 3, 4, 5, 6])
array('d', [1.3, 1.5, 1.8])


# Insertion

In [8]:
a1.insert(2,9)
print(a1)

array('i', [1, 2, 9, 3, 4, 5, 6])


# Time Complexity: O(1), O(n)

# Traversal Operation

In [9]:
def traversearray(array):
    for i in array:
        print(i)
print(traversearray(a1))

1
2
9
3
4
5
6
None


# Time Complexity: O(n), space complexity: O(1)

# Access array element

In [12]:
def accesselement(array, index):
    if index >= len(array):
        print('There is not any element in this index')
    else:
        print(array[index])
print(accesselement(a1,3))
print(accesselement(a1,8))

3
None
There is not any element in this index
None


# Time complexity: O(1), space complexity: O(1)

# Searching for an element

In [13]:
def searchinarray(array,value):
    for i in array:
        if i == value:
            return array.index(value)
    return "The element is not available"
print(searchinarray(a1,3))
print(searchinarray(a1,8))

3
The element is not available


# Time Complexity: O(n), space complexity: O(1)

# Deleting an element

In [14]:
print(a1)
a1.remove(6)
print(a1)

array('i', [1, 2, 9, 3, 4, 5, 6])
array('i', [1, 2, 9, 3, 4, 5])


# Time complexity: O(1) / O(n), space complexity: O(1)

# 2D Array

In [16]:
import numpy as np
a2 = np.array([[1,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(a2)

[[ 1 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


# Time  complexity for creating: O(1), space complexity: O(mn)

# Insertion

In [20]:
a3= np.insert(a2,0,[[1,2,3,4]],axis=1) # column
print(a3)
a3= np.insert(a2,0,[[1,2,3,4]],axis=0)
print(a3)
a4 = np.append(a2,[[6,7,8,9]], axis=0) # row
print(a4)

[[ 1  1 15 10  6]
 [ 2 10 14 11  5]
 [ 3 12 17 12  8]
 [ 4 15 18 14  9]]
[[ 1  2  3  4]
 [ 1 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[ 1 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 6  7  8  9]]


# Time Complexity: O(mn) O(1), space complexity: O(1)

# Accessing an element

In [21]:
def accesselement(array, rowindex, colindex):
    if rowindex >= len(array) or colindex >= len(array[0]):
        print('Incorrect index')
    else:
        print(array[rowindex][colindex])
accesselement(a2,1,2)

11


# Time complexity: O(1), space complexity: O(1)

# Traversal

In [23]:
def traverse2darray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
                       print(array[i][j])
print(traverse2darray(a2))

1
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9
None


# Time Complexity: O(mn) , space complexity: O(1)

# searching an element

In [26]:
def search2darray(array, value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return 'The value is at '+str(i)+""+str(j)
    return 'Not Found'
print(search2darray(a2,17))
print(search2darray(a2,175))

The value is at 21
Not Found


# Time complexity: O(mn), space complexity: O(1)

# Deletion

In [29]:
a5 = np.delete(a2,0,axis=0) # row deletion
print(a2)
print("\N{winking face}")
print(a5)

[[ 1 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
😉
[[10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


# Time complexity: O(mn), space complexity: O(1)